# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pingpong.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pingpong.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0epingpong.proto\"\x1a\n\x07RPCPing\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\x07RPCPong\x12\x0f\n\x07message\x18\x01 \x01(\t2(\n\x08PingPong\x12\x1c\n\x04\x63\x61ll\x12\x08.RPCPing\x1a\x08.RPCPong\"\x00\x62\x06proto3')
)




_RPCPING = _descriptor.Descriptor(
  name='RPCPing',
  full_name='RPCPing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='RPCPing.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=44,
)


_RPCPONG = _descriptor.Descriptor(
  name='RPCPong',
  full_name='RPCPong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='RPCPong.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['RPCPing'] = _RPCPING
DESCRIPTOR.message_types_by_name['RPCPong'] = _RPCPONG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPCPing = _reflection.GeneratedProtocolMessageType('RPCPing', (_message.Message,), dict(
  DESCRIPTOR = _RPCPING,
  __module__ = 'pingpong_pb2'
  # @@protoc_insertion_point(class_scope:RPCPing)
  ))
_sym_db.RegisterMessage(RPCPing)

RPCPong = _reflection.GeneratedProtocolMessageType('RPCPong', (_message.Message,), dict(
  DESCRIPTOR = _RPCPONG,
  __module__ = 'pingpong_pb2'
  # @@protoc_insertion_point(class_scope:RPCPong)
  ))
_sym_db.RegisterMessage(RPCPong)



_PINGPONG = _descriptor.ServiceDescriptor(
  name='PingPong',
  full_name='PingPong',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=74,
  serialized_end=114,
  methods=[
  _descriptor.MethodDescriptor(
    name='call',
    full_name='PingPong.call',
    index=0,
    containing_service=None,
    input_type=_RPCPING,
    output_type=_RPCPONG,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PINGPONG)

DESCRIPTOR.services_by_name['PingPong'] = _PINGPONG

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class PingPongStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.call = channel.unary_unary(
          '/PingPong/call',
          request_serializer=RPCPing.SerializeToString,
          response_deserializer=RPCPong.FromString,
          )


  class PingPongServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def call(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_PingPongServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'call': grpc.unary_unary_rpc_method_handler(
            servicer.call,
            request_deserializer=RPCPing.FromString,
            response_serializer=RPCPong.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'PingPong', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaPingPongServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def call(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaPingPongStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def call(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    call.future = None


  def beta_create_PingPong_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('PingPong', 'call'): RPCPing.FromString,
    }
    response_serializers = {
      ('PingPong', 'call'): RPCPong.SerializeToString,
    }
    method_implementations = {
      ('PingPong', 'call'): face_utilities.unary_unary_inline(servicer.call),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_PingPong_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('PingPong', 'call'): RPCPing.SerializeToString,
    }
    response_deserializers = {
      ('PingPong', 'call'): RPCPong.FromString,
    }
    cardinalities = {
      'call': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'PingPong', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
